### ISSUE TITLE
Error with Jassi

### ISSUE THREAD

**Issue by llooFlashooll** [Aurore54F/lexical-jsdetector#1]
I think this reimplementation of Cujo leverages the lexer for JavaScript code `Jassi`. But this Jassi repo is old, and I can't build it on my Ubuntu18.04 system. Therefore I can't build up this entire project.

**Comment by Aurore54F** [comment]
Thanks for reaching out! I'm not sure how I can help you, as `Jassi` is not maintained by me. Which error do you get?

**Comment by llooFlashooll** [comment]
When I clone the `Jassi` repo. I can't build up by running the cmd `./bootstrap`, `./configure` and `make`. In this Jassi repo, they don't even have the correct `configure` and `Makefile` I think.

**Comment by Aurore54F** [comment]
I'm not sure how I can help you? Did you perhaps try on a VM with an older Ubuntu system?
